global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scrapper-metrics'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'bot-metrics'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8082']
