/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;


import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubLinkInfo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GithubLinkInfoRecord extends UpdatableRecordImpl<GithubLinkInfoRecord> implements Record9<Integer, Long, String, String, Boolean, Long, Long, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.github_link_info.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.github_link_info.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.github_link_info.link_id</code>.
     */
    public void setLinkId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.github_link_info.link_id</code>.
     */
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.github_link_info.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.github_link_info.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.github_link_info.owner_name</code>.
     */
    public void setOwnerName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.github_link_info.owner_name</code>.
     */
    public String getOwnerName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.github_link_info.fork</code>.
     */
    public void setFork(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.github_link_info.fork</code>.
     */
    public Boolean getFork() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.github_link_info.forks_count</code>.
     */
    public void setForksCount(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.github_link_info.forks_count</code>.
     */
    public Long getForksCount() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.github_link_info.watchers_count</code>.
     */
    public void setWatchersCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.github_link_info.watchers_count</code>.
     */
    public Long getWatchersCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.github_link_info.pushed_at</code>.
     */
    public void setPushedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.github_link_info.pushed_at</code>.
     */
    public OffsetDateTime getPushedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.github_link_info.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.github_link_info.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Long, String, String, Boolean, Long, Long, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Long, String, String, Boolean, Long, Long, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GithubLinkInfo.GITHUB_LINK_INFO.ID;
    }

    @Override
    public Field<Long> field2() {
        return GithubLinkInfo.GITHUB_LINK_INFO.LINK_ID;
    }

    @Override
    public Field<String> field3() {
        return GithubLinkInfo.GITHUB_LINK_INFO.NAME;
    }

    @Override
    public Field<String> field4() {
        return GithubLinkInfo.GITHUB_LINK_INFO.OWNER_NAME;
    }

    @Override
    public Field<Boolean> field5() {
        return GithubLinkInfo.GITHUB_LINK_INFO.FORK;
    }

    @Override
    public Field<Long> field6() {
        return GithubLinkInfo.GITHUB_LINK_INFO.FORKS_COUNT;
    }

    @Override
    public Field<Long> field7() {
        return GithubLinkInfo.GITHUB_LINK_INFO.WATCHERS_COUNT;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return GithubLinkInfo.GITHUB_LINK_INFO.PUSHED_AT;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return GithubLinkInfo.GITHUB_LINK_INFO.CREATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getLinkId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getOwnerName();
    }

    @Override
    public Boolean component5() {
        return getFork();
    }

    @Override
    public Long component6() {
        return getForksCount();
    }

    @Override
    public Long component7() {
        return getWatchersCount();
    }

    @Override
    public OffsetDateTime component8() {
        return getPushedAt();
    }

    @Override
    public OffsetDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getLinkId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getOwnerName();
    }

    @Override
    public Boolean value5() {
        return getFork();
    }

    @Override
    public Long value6() {
        return getForksCount();
    }

    @Override
    public Long value7() {
        return getWatchersCount();
    }

    @Override
    public OffsetDateTime value8() {
        return getPushedAt();
    }

    @Override
    public OffsetDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public GithubLinkInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value2(Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value4(String value) {
        setOwnerName(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value5(Boolean value) {
        setFork(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value6(Long value) {
        setForksCount(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value7(Long value) {
        setWatchersCount(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value8(OffsetDateTime value) {
        setPushedAt(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord value9(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GithubLinkInfoRecord values(Integer value1, Long value2, String value3, String value4, Boolean value5, Long value6, Long value7, OffsetDateTime value8, OffsetDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubLinkInfoRecord
     */
    public GithubLinkInfoRecord() {
        super(GithubLinkInfo.GITHUB_LINK_INFO);
    }

    /**
     * Create a detached, initialised GithubLinkInfoRecord
     */
    public GithubLinkInfoRecord(Integer id, Long linkId, String name, String ownerName, Boolean fork, Long forksCount, Long watchersCount, OffsetDateTime pushedAt, OffsetDateTime createdAt) {
        super(GithubLinkInfo.GITHUB_LINK_INFO);

        setId(id);
        setLinkId(linkId);
        setName(name);
        setOwnerName(ownerName);
        setFork(fork);
        setForksCount(forksCount);
        setWatchersCount(watchersCount);
        setPushedAt(pushedAt);
        setCreatedAt(createdAt);
    }
}
