/*
 * This file is generated by jOOQ.
 */

package ru.tinkoff.edu.java.scrapper.domain.jooq.tables.records;

import java.time.OffsetDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LinkRecord extends UpdatableRecordImpl<LinkRecord>
    implements Record5<Integer, Long, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.link.link_id</code>.
     */
    public void setLinkId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.link.link_id</code>.
     */
    public Integer getLinkId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.link.tg_chat_id</code>.
     */
    public void setTgChatId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.link.tg_chat_id</code>.
     */
    public Long getTgChatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.link.url</code>.
     */
    public void setUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.link.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.link.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.link.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.link.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.link.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Long, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Long, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Link.LINK.LINK_ID;
    }

    @Override
    public Field<Long> field2() {
        return Link.LINK.TG_CHAT_ID;
    }

    @Override
    public Field<String> field3() {
        return Link.LINK.URL;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return Link.LINK.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Link.LINK.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getLinkId();
    }

    @Override
    public Long component2() {
        return getTgChatId();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getLinkId();
    }

    @Override
    public Long value2() {
        return getTgChatId();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public LinkRecord value1(Integer value) {
        setLinkId(value);
        return this;
    }

    @Override
    public LinkRecord value2(Long value) {
        setTgChatId(value);
        return this;
    }

    @Override
    public LinkRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public LinkRecord value4(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public LinkRecord value5(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public LinkRecord values(Integer value1, Long value2, String value3, OffsetDateTime value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinkRecord
     */
    public LinkRecord() {
        super(Link.LINK);
    }

    /**
     * Create a detached, initialised LinkRecord
     */
    public LinkRecord(Integer linkId, Long tgChatId, String url, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Link.LINK);

        setLinkId(linkId);
        setTgChatId(tgChatId);
        setUrl(url);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
