app:
  test: helloFromScrapper
  gitHubToken: ${TOKEN}
  scheduler:
    interval: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

bot:
  base-url: http://localhost:8080

spring:
  liquibase:
    enabled: false
  datasource:
    username: tracker-user
    password: 123456
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true