app:
  test: helloFromScrapper
  gitHubToken: ${TOKEN}
  databaseAccessType: jdbc
  scheduler:
    interval: 5000
  useQueue: true
  rabbitmq:
    queueName: scrapper_queue
    topicExchangeName: scrapper_exchange
    deadLetterTopicExchangeName: scrapper_exchange_dead
    deadLetterRoutingKey: scrapper_exchange_rk

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

bot:
  base-url: http://localhost:8080

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    username: tracker-user
    password: 123456
    url: jdbc:postgresql://localhost:5432/scrapper
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

management:
  server:
    port: 8083
  endpoints:
    web:
      path-mapping:
        prometheus: metrics
      basePath: /
      exposure:
        include: info,health,prometheus
  endpoint:
    shutdown:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      enabled: true
      prometheus:
        enabled: true

