/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Databasechangelog;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Databasechangeloglock;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.GithubLinkInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.Link;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.StackoverflowLinkInfo;
import ru.tinkoff.edu.java.scrapper.domain.jooq.tables.TgChat;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.github_link_info</code>.
     */
    public static final GithubLinkInfo GITHUB_LINK_INFO = GithubLinkInfo.GITHUB_LINK_INFO;

    /**
     * The table <code>public.link</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>public.stackoverflow_link_info</code>.
     */
    public static final StackoverflowLinkInfo STACKOVERFLOW_LINK_INFO = StackoverflowLinkInfo.STACKOVERFLOW_LINK_INFO;

    /**
     * The table <code>public.tg_chat</code>.
     */
    public static final TgChat TG_CHAT = TgChat.TG_CHAT;
}
