version: '3'
services:
  postgres:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: tracker-user
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    platform: linux/amd64
    depends_on:
      - postgres
    command:
      - --hub-mode=off
      - --changelog-file=./master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgres:5432/scrapper
      - --username=tracker-user
      - --password=123456
      - update
    volumes:
      - ./src/main/resources/migrations:/liquibase/changelog
    restart: unless-stopped
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=tracker-user
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    networks:
      - backend


volumes:
  db-data:
  rabbit_data:

networks:
  backend:
